# Generated by Django 2.1 on 2020-10-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, upload_to='images/')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('summary', models.TextField()),
                ('author', models.TextField()),
                ('book_report', models.TextField()),
                ('paragraph', models.TextField()),
            ],
        ),
    ]
