# Generated by Django 2.1 on 2020-10-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20201006_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='paragraph',
            new_name='information',
        ),
    ]
