# Generated by Django 2.1 on 2020-10-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20201006_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='information',
        ),
    ]
