# Generated by Django 2.1 on 2020-10-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_auto_20201007_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='summary',
            new_name='body',
        ),
    ]
