# Generated by Django 2.1 on 2020-10-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_auto_20201018_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='grade',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
