# Generated by Django 2.1 on 2020-10-22 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_auto_20201020_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(max_length=255)),
                ('page', models.SmallIntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Book')),
            ],
        ),
    ]
