# Generated by Django 2.1 on 2020-10-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='approved_open',
            field=models.BooleanField(default=False),
        ),
    ]
