# Generated by Django 2.1 on 2020-10-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_auto_20201024_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='page',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
